#include <a_samp>

//Defines

#define END                                                                     ;

#define OR_IF 									elseif

#define OTHERWISE                                                               else

#define YES                                                                     1

#define NO 									0

#define PLAYER 									playerid

#define VARIABLE                                                                new

#define VAR                                              		        new

#define IS_EQUAL_TO 								==

#define IS_GREATER_THAN 							>

#define IS_LESS_THAN 								<

#define IS_GREATER_OR_EQUAL 							>=

#define IS_LESS_OR_EQUAL 							<=

#define ADD 									+

#define SUBTRACT 								-

#define MULTIPLY                                                                *

#define DIVIDE                                                                  /

#define NULL 									0

#define SET_VALUE_TO 								=

#define SET                                                                     enum

#define ARRAY_END                                                               };

#define RETURN_VALUE                                                            return

#define LOG_CONSOLE                                                             print

#define function                                                                public
